# Generated by Django 5.0.7 on 2024-08-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_main', '0002_empa_emps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Level S', 'Level A')], max_length=255, null=True),
        ),
    ]
